name: Build

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run unit tests
        run: go test ./...

  deploy-to-heroku:
    name: Deploy to Heroku
    needs: Test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    env:
      HEROKU_APP: ${{ secrets.HEROKU_APP }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - uses: actions/checkout@v1
      - name: Login to Heroku Container registry
        run: heroku container:login
      - name: Build and push
        run: heroku container:push -a $HEROKU_APP web
      - name: Release
        run: heroku container:release -a $HEROKU_APP web
